#ifndef SINGULAR_POTENTIAL_PREPROCESSOR_HPP
#define SINGULAR_POTENTIAL_PREPROCESSOR_HPP

#if SINGULAR_POTENTIAL_HEADER_ONLY
    #define SINGULAR_POTENTIAL_EXTERNAL_LINKAGE inline
    #define SINGULAR_POTENTIAL_INTERNAL_LINKAGE inline
#else
    #define SINGULAR_POTENTIAL_EXTERNAL_LINKAGE
    #define SINGULAR_POTENTIAL_INTERNAL_LINKAGE static
#endif

#endif
